/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    EmailVerificationPrompt: typeof import('./src/components/auth/EmailVerificationPrompt.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    LoadingScreen: typeof import('./src/components/ui/LoadingScreen.vue')['default']
    RightSidebar: typeof import('./src/components/layout/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
