/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    EmailVerificationPrompt: typeof import('./src/components/auth/EmailVerificationPrompt.vue')['default']
    ErrorToast: typeof import('./src/components/notifications/ErrorToast.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    LoadingScreen: typeof import('./src/components/ui/LoadingScreen.vue')['default']
    QuickMenuWindow: typeof import('./src/components/layout/right-sidebar/QuickMenuWindow.vue')['default']
    RightSidebar: typeof import('./src/components/layout/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsWindow: typeof import('./src/components/layout/right-sidebar/SettingsWindow.vue')['default']
  }
}
