/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/account-manage': RouteRecordInfo<'/account/account-manage', '/account/account-manage', Record<never, never>, Record<never, never>>,
    '/account/manage-profile': RouteRecordInfo<'/account/manage-profile', '/account/manage-profile', Record<never, never>, Record<never, never>>,
    '/account/profile': RouteRecordInfo<'/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/color-view': RouteRecordInfo<'/admin/color-view', '/admin/color-view', Record<never, never>, Record<never, never>>,
    '/admin/menu': RouteRecordInfo<'/admin/menu', '/admin/menu', Record<never, never>, Record<never, never>>,
    '/admin/new-template': RouteRecordInfo<'/admin/new-template', '/admin/new-template', Record<never, never>, Record<never, never>>,
    '/dash/': RouteRecordInfo<'/dash/', '/dash', Record<never, never>, Record<never, never>>,
    '/data/': RouteRecordInfo<'/data/', '/data', Record<never, never>, Record<never, never>>,
    '/data/cik-mapping': RouteRecordInfo<'/data/cik-mapping', '/data/cik-mapping', Record<never, never>, Record<never, never>>,
    '/data/data-viewer': RouteRecordInfo<'/data/data-viewer', '/data/data-viewer', Record<never, never>, Record<never, never>>,
    '/data/gemini': RouteRecordInfo<'/data/gemini', '/data/gemini', Record<never, never>, Record<never, never>>,
    '/data/populate-10K-data': RouteRecordInfo<'/data/populate-10K-data', '/data/populate-10K-data', Record<never, never>, Record<never, never>>,
    '/data/upload': RouteRecordInfo<'/data/upload', '/data/upload', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/refactor': RouteRecordInfo<'/refactor', '/refactor', Record<never, never>, Record<never, never>>,
    '/template-plain': RouteRecordInfo<'/template-plain', '/template-plain', Record<never, never>, Record<never, never>>,
    '/test/': RouteRecordInfo<'/test/', '/test', Record<never, never>, Record<never, never>>,
    '/test/10k-parser-test': RouteRecordInfo<'/test/10k-parser-test', '/test/10k-parser-test', Record<never, never>, Record<never, never>>,
    '/test/blob-upload-test': RouteRecordInfo<'/test/blob-upload-test', '/test/blob-upload-test', Record<never, never>, Record<never, never>>,
    '/test/configuration-viewer': RouteRecordInfo<'/test/configuration-viewer', '/test/configuration-viewer', Record<never, never>, Record<never, never>>,
    '/test/edgar-composable-test': RouteRecordInfo<'/test/edgar-composable-test', '/test/edgar-composable-test', Record<never, never>, Record<never, never>>,
    '/test/edgar-test': RouteRecordInfo<'/test/edgar-test', '/test/edgar-test', Record<never, never>, Record<never, never>>,
    '/test/gemini': RouteRecordInfo<'/test/gemini', '/test/gemini', Record<never, never>, Record<never, never>>,
    '/test/layout-test': RouteRecordInfo<'/test/layout-test', '/test/layout-test', Record<never, never>, Record<never, never>>,
    '/test/login-ok': RouteRecordInfo<'/test/login-ok', '/test/login-ok', Record<never, never>, Record<never, never>>,
    '/test/new-template': RouteRecordInfo<'/test/new-template', '/test/new-template', Record<never, never>, Record<never, never>>,
    '/test/notification-test': RouteRecordInfo<'/test/notification-test', '/test/notification-test', Record<never, never>, Record<never, never>>,
    '/test-dal': RouteRecordInfo<'/test-dal', '/test-dal', Record<never, never>, Record<never, never>>,
  }
}
