<template>
  <v-container>
    <v-row>
      <v-col cols="12">
        <h1>Configuration Test Viewer</h1>
        <p>Generated by Toolbench Configuration Manager</p>
        <p>If colors show correctly, the settings.scss file is working.</p>
      </v-col>
    </v-row>
    
    <v-row>
      <v-col cols="12">
        <v-card>
          <v-card-title>Color Test</v-card-title>
          <v-card-text>
      <v-btn color="primary" class="ma-2">Primary (#875330)</v-btn>
      <v-btn color="secondary" class="ma-2">Secondary (#446C5C)</v-btn>
      <v-btn color="success" class="ma-2">Success (#7AB77D)</v-btn>
      <v-btn color="warning" class="ma-2">Warning (#DCB478)</v-btn>
      <v-btn color="error" class="ma-2">Error (#D5746D)</v-btn>
      <v-btn color="info" class="ma-2">Info (#AEC5D7)</v-btn>
      <v-btn color="terracotta" class="ma-2">terracotta (#8F7565)</v-btn>
      <v-btn color="sand" class="ma-2">sand (#8F7565)</v-btn>
      <v-btn color="alpine-blue" class="ma-2">alpine-blue (#8F7565)</v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
// Static test page
</script>